"""Generate static completions from the public argparse tree; no config/backend I/O."""

from __future__ import annotations

import argparse
import shlex


def _contexts(parser: argparse.ArgumentParser, path: str = "") -> dict:
    result = {path: {"words": [], "options": [], "values": {}, "files": [], "children": []}}
    node = result[path]
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            node["children"].extend(action.choices)
            node["words"].extend(action.choices)
            for name, child in action.choices.items():
                result.update(_contexts(child, " ".join(filter(None, (path, name)))))
        elif action.option_strings:
            node["options"].extend(action.option_strings)
            if action.nargs != 0:
                for option in action.option_strings:
                    node["values"][option] = list(action.choices or [])
                    if action.dest in {"config", "output", "inventory", "package", "root", "plugins_dir", "provisioning_dir"}:
                        node["files"].append(option)
        elif action.choices:
            node["words"].extend(action.choices)
    return result


def generate(parser: argparse.ArgumentParser, shell: str) -> str:
    contexts = _contexts(parser)
    transitions = [(path + "|" + child, " ".join(filter(None, (path, child))))
                   for path, node in contexts.items() for child in node["children"]]
    value_options = sorted({opt for node in contexts.values() for opt in node["values"]})
    if shell == "fish":
        lines = ["# Generated by xltel completion fish", "function __xltel_context",
                 "    set -l context ''", "    set -l skip 0", "    set -l tokens (commandline -opc)",
                 "    for word in $tokens[2..-1]", "        if test $skip = 1; set skip 0; continue; end",
                 "        if test \"$word\" = --; echo __workload__; return; end", "        switch $word",
                 "            case " + " ".join(shlex.quote(opt) for opt in value_options),
                 "                set skip 1; continue", "        end", "        switch \"$context|$word\""]
        for pattern, child in transitions:
            lines += [f"            case '{pattern}'", f"                set context '{child}'"]
        lines += ["        end", "    end", "    if test -z \"$context\"; echo __root__; else; echo $context; end", "end"]
        for path, node in contexts.items():
            condition = shlex.quote(f'test (__xltel_context) = "{path or "__root__"}"')
            if node["words"]:
                lines.append(f"complete -c xltel -n {condition} -f -a '{' '.join(node['words'])}'")
            for option in node["options"]:
                spec = "-l " + option[2:] if option.startswith("--") else "-s " + option[1:]
                values = node["values"].get(option)
                extra = " -r" if values is not None else ""
                if values:
                    extra += " -f -a '" + " ".join(values) + "'"
                if option in node["files"]:
                    extra += " -F"
                lines.append(f"complete -c xltel -n {condition} {spec}{extra}")
        return "\n".join(lines) + "\n"
    if shell not in {"bash", "zsh"}:
        raise ValueError("Unknown completion shell")
    zsh = shell == "zsh"
    lines = ["# Generated by xltel completion " + shell, "_xltel() {",
             "    local context='' word previous current candidates='' i"]
    if zsh:
        lines += ["    local -a replies", '    current="${words[CURRENT]}"', '    previous="${words[CURRENT-1]}"',
                  "    for ((i=2; i<CURRENT; i++)); do", '        word="${words[i]}"']
    else:
        lines += ['    current="${COMP_WORDS[COMP_CWORD]}"', '    previous="${COMP_WORDS[COMP_CWORD-1]}"',
                  "    COMPREPLY=()", "    for ((i=1; i<COMP_CWORD; i++)); do", '        word="${COMP_WORDS[i]}"']
    lines += ['        [[ "$word" != -- ]] || return 0', '        case "$word" in',
              "            " + "|".join(value_options) + ") ((i+=1)); continue ;;", "        esac",
              '        case "$context|$word" in']
    for pattern, child in transitions:
        lines.append(f"            '{pattern}') context='{child}' ;;")
    lines += ["        esac", "    done", '    case "$context|$previous" in']
    for path, node in contexts.items():
        for option, choices in node["values"].items():
            pattern = shlex.quote(path + "|" + option)
            if option in node["files"]:
                action = "_files" if zsh else 'mapfile -t COMPREPLY < <(compgen -f -- "$current")'
            elif choices:
                action = "compadd -- " + " ".join(choices) if zsh else 'mapfile -t COMPREPLY < <(compgen -W "' + " ".join(choices) + '" -- "$current")'
            else:
                action = ":"
            lines.append(f"        {pattern}) {action}; return 0 ;;")
    lines += ["    esac", '    case "$context" in']
    for path, node in contexts.items():
        lines.append(f"        '{path}') candidates='{' '.join(node['words'] + node['options'])}' ;;")
    lines += ["    esac"]
    if zsh:
        lines += ["    replies=(${=candidates})", "    compadd -- \"${replies[@]}\"", "    _files", "}", "compdef _xltel xltel"]
    else:
        lines += ['    mapfile -t COMPREPLY < <(compgen -W "$candidates" -- "$current")',
                  "}", "complete -o default -F _xltel xltel"]
    return "\n".join(lines) + "\n"
